---
- name: create the backend directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: get extracted artifact into backend
  unarchive: # unarchive a file in src to dest
    src: ~/project/artifact.tar.gz
    dest: ~/backend  # remote EC2
    mode: 0755
    owner: ubuntu
    group: ubuntu

# - name: copy zipped artifact
#   become: yes
#   copy:
#     src: ~/project/artifact.tar.gz
#     dest: ~/artifact.tar.gz  

# - name: execute node
#   shell: |
#     # tar -xvzf artifact.tar.gz
#     cd backend
#     npm install
#     pm2 stop default
#     pm2 start npm -- start

- name: execute node
  shell: |
    cd backend
    curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build
    sudo pm2 start npm --name backend -- start
