Description: >
  backend stack for udapeople-project

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030  # API
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp  # Node-Exporter
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      # KeyName: ubuntu
      KeyName: udapeople-key
      ImageId: ami-000722651477bd39b  # ubuntu 20.04 for us-east 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
