global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # using Prometheus Service Discovery feature, to Automatically add exporters on EC2 instance
  # give credentials of IAM user with programatic access & ability to "EC2-read-only"
  - job_name: 'Prometheus-EC2-node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: 
        secret_key: 
        port: 9100

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
