---
- name: Setup/Configure EC2(Ubuntu) for Prometheus
  hosts: all
  user: ubuntu
  become: true
  
  pre_tasks:
    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes
    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: "yes"
    - name: remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes
  
  roles:
    - setup-prometheus-server
    - setup-prometheus-exporter
